### ISSUE TITLE
opens doesn't update in db. app logs error

### ISSUE THREAD

**Issue by arjunnn** [arjunnn/linkss#1]
<details>
 <summary>
   Error and Stack trace:
 </summary>
   RequestError: Requests can only be made in the LoggedIn state, not the SentClientRequest state
    at RequestError (C:\Users\arjun\Documents\GitHub\linkss\node_modules\tedious\lib\errors.js:34:12)
    at Connection.makeRequest (C:\Users\arjun\Documents\GitHub\linkss\node_modules\tedious\lib\connection.js:1108:33)
    at Connection.execSql (C:\Users\arjun\Documents\GitHub\linkss\node_modules\tedious\lib\connection.js:898:19)
    at incrementOpens (C:\Users\arjun\Documents\GitHub\linkss\app.js:92:14)
    at C:\Users\arjun\Documents\GitHub\linkss\app.js:57:3
    at Layer.handle [as handle_request] (C:\Users\arjun\Documents\GitHub\linkss\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\arjun\Documents\GitHub\linkss\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\arjun\Documents\GitHub\linkss\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\arjun\Documents\GitHub\linkss\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\arjun\Documents\GitHub\linkss\node_modules\express\lib\router\index.js:281:22
  message: 'Requests can only be made in the LoggedIn state, not the SentClientRequest state',
  code: 'EINVALIDSTATE'
</details>

**Comment by arjunnn** [comment]
fixed by https://github.com/arjunnn/linkss/commit/eb257bb4ac2dd762a68e98abcacec0c1fd62ece1
